# Generated by Django 3.1.4 on 2021-01-18 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_auto_20210118_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
